- purl: pkg:deb/ubuntu/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1ubuntu0.1~esm1?arch=source&distro=esm-apps/jammy
  affected_by_advisories:
    - ubuntu_osv/UBUNTU-CVE-2021-20178
    - ubuntu_osv/UBUNTU-CVE-2021-20180
    - ubuntu_osv/UBUNTU-CVE-2021-20191
    - ubuntu_osv/UBUNTU-CVE-2021-20228
    - ubuntu_osv/UBUNTU-CVE-2021-3447
    - ubuntu_osv/UBUNTU-CVE-2021-3532
    - ubuntu_osv/UBUNTU-CVE-2021-3533
    - ubuntu_osv/UBUNTU-CVE-2022-2568
    - ubuntu_osv/UBUNTU-CVE-2022-3697
    - ubuntu_osv/UBUNTU-CVE-2024-11079
    - ubuntu_osv/UBUNTU-CVE-2024-8775
    - ubuntu_osv/UBUNTU-CVE-2025-14010
  fixing_advisories:
    - ubuntu_osv/UBUNTU-CVE-2021-3583
    - ubuntu_osv/UBUNTU-CVE-2021-3620
