- purl: pkg:deb/ubuntu/ansible@1.9.2%2Bdfsg-2?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv/UBUNTU-CVE-2016-3096
    - ubuntu_osv/UBUNTU-CVE-2016-8628
    - ubuntu_osv/UBUNTU-CVE-2016-9587
    - ubuntu_osv/UBUNTU-CVE-2018-10875
    - ubuntu_osv/UBUNTU-CVE-2018-16837
  fixing_advisories: []
- purl: pkg:deb/ubuntu/ansible@1.9.2%2Bdfsg-2?arch=source&distro=esm-apps/xenial
  affected_by_advisories:
    - ubuntu_osv/UBUNTU-CVE-2016-8614
    - ubuntu_osv/UBUNTU-CVE-2019-10206
    - ubuntu_osv/UBUNTU-CVE-2019-14846
    - ubuntu_osv/UBUNTU-CVE-2019-14904
    - ubuntu_osv/UBUNTU-CVE-2021-20178
    - ubuntu_osv/UBUNTU-CVE-2021-20180
    - ubuntu_osv/UBUNTU-CVE-2021-20191
    - ubuntu_osv/UBUNTU-CVE-2021-20228
    - ubuntu_osv/UBUNTU-CVE-2021-3447
    - ubuntu_osv/UBUNTU-CVE-2021-3583
    - ubuntu_osv/UBUNTU-CVE-2022-2568
    - ubuntu_osv/UBUNTU-CVE-2024-11079
    - ubuntu_osv/UBUNTU-CVE-2024-8775
    - ubuntu_osv/UBUNTU-CVE-2025-14010
  fixing_advisories: []
