- purl: pkg:deb/ubuntu/ansible@2.0.0.2-2ubuntu1.3%2Besm6?arch=source&distro=esm-apps/xenial
  affected_by_advisories:
    - ubuntu_osv/UBUNTU-CVE-2021-20178
    - ubuntu_osv/UBUNTU-CVE-2021-20180
    - ubuntu_osv/UBUNTU-CVE-2021-20191
    - ubuntu_osv/UBUNTU-CVE-2021-20228
    - ubuntu_osv/UBUNTU-CVE-2021-3447
    - ubuntu_osv/UBUNTU-CVE-2022-2568
    - ubuntu_osv/UBUNTU-CVE-2024-11079
    - ubuntu_osv/UBUNTU-CVE-2024-8775
    - ubuntu_osv/UBUNTU-CVE-2025-14010
  fixing_advisories: []
